### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by sksar** [ThijmenGThN/directus-themebuilder#18]
The website link https://heuve.link/directus-themebuilder is down.

![Screenshot 2023-06-30 at 18 06 16](https://github.com/ThijmenGThN/directus-themebuilder/assets/11752260/47dc774a-2b80-4f0a-8c8b-b6f094fa9eed)

**Comment by ThijmenGThN** [comment]
Hi @sksar 👋

Thank you for opening this issue, I am aware of the website being offline. There are some server related issues on my end, this will be resolved as soon as possible.

Sorry for the inconvenience!

**Comment by ThijmenGThN** [comment]
Downtime is expected to last until July 2.

**Comment by sksar** [comment]
@ThijmenGThN 
Is the source code fully static site? Means can it be hosted somewhere like Vercel or Cloudflare Pages?

**Comment by ThijmenGThN** [comment]
> @ThijmenGThN 
> 
> Is the source code fully static site? Means can it be hosted somewhere like Vercel or Cloudflare Pages?

Unfortunately, this isn't react where it builds the app to be deployed on a webserver, this needs to run in a nodejs environment.

Nextjs's export function might be a solution. My entire infrastructure is currently out of internet, I can go in depth but long story short I'll regain access again on July 2.

**Comment by ThijmenGThN** [comment]
Hi @sksar 👋

The Theme Builder is back online, sorry for the inconvenience and thank you for being alert 😄
